/**
 * `/api/v1/webhooks` — register and list webhook endpoints (M6).
 * Scope: `webhooks:manage`.
 *
 *   GET  /api/v1/webhooks    the endpoints this workspace has registered
 *   POST /api/v1/webhooks    register one, and read its signing secret once
 *
 * The signing secret follows the same rule the API token does: generated by the
 * server, returned exactly once, and never readable again. It *is* stored — an
 * HMAC cannot be computed from a hash, which `webhook-rules.ts` states out loud —
 * so the one-time display is what keeps a console from leaking it later, and
 * rotation is what a customer does when they think it has.
 */

import type { NextRequest } from "next/server";

import { apiTokenServicesFor, webhookServicesFor } from "../../../../lib/db";
import { apiError, apiJson, gate, successHeaders } from "../../../../lib/public-api-http";
import { API_VERSION } from "../../../../lib/public-api-rules";
import { send } from "../_respond";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

function endpointView(endpoint: {
  id: string;
  name: string;
  url: string;
  events: readonly string[];
  enabled: boolean;
  createdAt: string;
  disabledAt: string | null;
}): Record<string, unknown> {
  return {
    id: endpoint.id,
    name: endpoint.name,
    url: endpoint.url,
    events: [...endpoint.events],
    enabled: endpoint.enabled,
    created_at: endpoint.createdAt,
    disabled_at: endpoint.disabledAt,
  };
}

export async function GET(request: NextRequest): Promise<Response> {
  const result = await gate(request, apiTokenServicesFor(), "webhooks:manage");
  if (!result.ok) return send(result.response);

  const listed = await webhookServicesFor().list(result.caller.actor);
  if (!listed.ok) return send(apiError(403, "forbidden", listed.error));
  return send(
    apiJson(200, { api_version: API_VERSION, data: listed.value.map(endpointView) }, successHeaders(result.caller)),
  );
}

export async function POST(request: NextRequest): Promise<Response> {
  const result = await gate(request, apiTokenServicesFor(), "webhooks:manage");
  if (!result.ok) return send(result.response);

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return send(apiError(400, "invalid_json", "Expected a JSON body."));
  }

  const created = await webhookServicesFor().register(result.caller.actor, {
    name: typeof body.name === "string" ? body.name : "",
    url: typeof body.url === "string" ? body.url : "",
    events: Array.isArray(body.events) ? (body.events as string[]) : [],
  });
  if (!created.ok) return send(apiError(422, "invalid_endpoint", created.error));

  return send(
    apiJson(
      201,
      {
        api_version: API_VERSION,
        data: endpointView(created.value.endpoint),
        secret: created.value.secret,
        secret_shown_once: "This is the only time this value can be read. Store it now.",
      },
      successHeaders(result.caller),
    ),
  );
}
