/**
 * Generated scenarios must be indistinguishable from hand-written ones, so the central
 * assertion here is: whatever the generator writes passes the same validation the hand-written
 * scenarios pass.
 *
 * Ported from `OnTrak-dev/tests/test_generator.py`. The one test shape that could not come
 * across as written is the duplicate-objective case: the Python monkeypatched the module's
 * `PRIMITIVES` dict to inject a clashing primitive, and this port's registry is read-only by
 * design (`primitives.ts` — registration is the only way in, and a duplicate id is refused).
 * The same fact is asserted with a real double: `suggestedCombinations()` contains the lab's
 * own self-pair, and generating it is refused for exactly the reason the monkeypatch test
 * existed — the same objective id cannot be graded twice.
 *
 *   npx tsx --tsconfig tests/tsconfig.json --test tests/lab-generator.test.ts
 */

import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { scenarioEntriesFrom } from "../src/lib/lab/dataset";
import { GenerationError, generate, generateMatrix, primitiveMatrix } from "../src/lib/lab/generator";
import { PRIMITIVES, getPrimitive } from "../src/lib/lab/primitives";
import { ScenarioRepository } from "../src/lib/lab/scenarios";

/** A scratch scenario tree, read back through the same loader a deployment uses. */
function scratchTree(): { root: string; load: () => ScenarioRepository; clean: () => void } {
  const root = mkdtempSync(join(tmpdir(), "ontrak-generator-"));
  return {
    root,
    load: (): ScenarioRepository => new ScenarioRepository(scenarioEntriesFrom(root)),
    clean: (): void => rmSync(root, { recursive: true, force: true }),
  };
}

test("generator: one primitive generates a scenario that validates", () => {
  const tree = scratchTree();
  try {
    const result = generate(["dns-resolver-trapped"], { root: tree.root });
    assert.deepEqual(result.problems, [], "the scenario passes the hand-written rules");
    assert.equal(result.ok, true);
    assert.equal(result.scenarioId, "dns-resolver-trapped");
    assert.ok(existsSync(join(result.directory, "scenario.json")));
    assert.ok(existsSync(join(result.directory, "setup.ps1")));
    assert.ok(existsSync(join(result.directory, "check.ps1")));

    const scenario = tree.load().get("dns-resolver-trapped");
    assert.equal(scenario.category, "network");
    assert.deepEqual(scenario.generatedFrom, ["dns-resolver-trapped"]);
    assert.deepEqual(
      scenario.objectives.map((objective) => objective.id),
      result.objectiveIds,
    );
    assert.equal(scenario.workload, "", "a generated scenario uses the site's golden image");
  } finally {
    tree.clean();
  }
});

test("generator: the scripts confirm success, write a report, and say where they came from", () => {
  const tree = scratchTree();
  try {
    const result = generate(["service-disabled"], { root: tree.root, scenarioId: "gen-spooler" });
    const setup = readFileSync(join(result.directory, "setup.ps1"), "utf8");
    const check = readFileSync(join(result.directory, "check.ps1"), "utf8");
    assert.match(setup, /Write-OnTrakSetupOk/);
    assert.match(setup, /OnTrak\.Common\.ps1/, "the setup dots in the shared library");
    assert.match(check, /OnTrak\.Common\.ps1/);
    assert.match(check, /Write-OnTrakReport/, "the check ends by writing the payload");
    assert.match(check, /Add-OnTrakCheck/, "and each objective is reported");
    assert.match(setup, /Generated by/, "provenance: regenerate rather than hand-edit");
    assert.match(check, /Generated by/);
  } finally {
    tree.clean();
  }
});

test("generator: a multi-fault ticket reads as one ticket, and adds up", () => {
  const tree = scratchTree();
  try {
    const result = generate(["dns-resolver-trapped", "app-config-corrupt"], {
      root: tree.root,
      scenarioId: "gen-broken-workstation",
      title: "Nothing works since this morning",
      intro: "The user reports the machine is unusable after a remote support session.",
    });
    assert.deepEqual(result.problems, []);
    const scenario = tree.load().get("gen-broken-workstation");
    assert.equal(scenario.title, "Nothing works since this morning");
    assert.match(scenario.briefing, /remote support session/, "the caller's intro is kept");
    assert.ok(scenario.objectives.length >= 4, "both faults' objectives are there");
    assert.equal(scenario.minutes, 40, "20 + 20");
    assert.equal(scenario.difficulty, 3, "the harder of the two, plus one for the combination");
    assert.ok(scenario.tags.includes("generated"));
    // The weights become a hundred-point budget, exactly.
    const total = scenario.objectives.reduce((sum, objective) => sum + objective.weight, 0);
    assert.equal(Math.round(total * 100) / 100, 100, "the weights total 100");
  } finally {
    tree.clean();
  }
});

test("generator: regenerating without force refuses to clobber, and force replaces", () => {
  const tree = scratchTree();
  try {
    generate(["service-disabled"], { root: tree.root, scenarioId: "one" });
    assert.throws(
      () => generate(["service-disabled"], { root: tree.root, scenarioId: "one" }),
      (error: unknown) => error instanceof GenerationError && /already exists/.test(error.message),
    );
    const forced = generate(["service-disabled"], { root: tree.root, scenarioId: "one", force: true });
    assert.deepEqual(forced.problems, []);
  } finally {
    tree.clean();
  }
});

test("generator: the refusals say what is wrong", () => {
  const tree = scratchTree();
  try {
    assert.throws(
      () => generate([], { root: tree.root }),
      /at least one fault primitive is required/,
    );
    assert.throws(
      () => generate(["service-disabled"], { root: tree.root, scenarioId: "Not Slugged" }),
      /must be lowercase and dash-separated/,
    );
    assert.throws(() => generate(["make-it-broken"], { root: tree.root }), /unknown fault primitive/);
    assert.throws(() => getPrimitive("make-it-broken"), /unknown fault primitive "make-it-broken"/);
  } finally {
    tree.clean();
  }
});

test("generator: the same objective id twice is refused rather than graded twice", () => {
  const tree = scratchTree();
  try {
    // The lab's own self-pair, which is exactly this case: two copies of one fault would
    // declare each objective twice, and the second would overwrite the first in the grade.
    const combo = ["malware-persistence", "malware-persistence"];
    assert.throws(
      () => generate(combo, { root: tree.root, scenarioId: "gen-double" }),
      (error: unknown) => error instanceof GenerationError && /appears twice/.test(error.message),
    );
  } finally {
    tree.clean();
  }
});

test("generator: validation can be skipped, and then nothing is claimed about the result", () => {
  const tree = scratchTree();
  try {
    const result = generate(["service-disabled"], { root: tree.root, scenarioId: "raw", validate: false });
    assert.deepEqual(result.problems, [], "no validator ran, so no problems were found");
    assert.ok(existsSync(join(result.directory, "scenario.json")));
  } finally {
    tree.clean();
  }
});

test("generator: the matrix generates a valid scenario for every primitive", () => {
  const tree = scratchTree();
  try {
    const results = generateMatrix({ root: tree.root, prefix: "gen" });
    assert.equal(results.length, PRIMITIVES.size, "one per primitive");
    const problems = results.flatMap((result) => result.problems);
    assert.deepEqual(problems, [], "every one passes the hand-written rules, scripts included");

    const ids = new Set(tree.load().list().map((scenario) => scenario.id));
    for (const result of results) {
      assert.ok(ids.has(result.scenarioId), `${result.scenarioId} is visible to the repository`);
    }
  } finally {
    tree.clean();
  }
});

test("generator: the matrix is repeatable", () => {
  const tree = scratchTree();
  try {
    const first = generateMatrix({ root: tree.root, prefix: "gen" });
    const second = generateMatrix({ root: tree.root, prefix: "gen", force: true });
    assert.deepEqual(
      first.map((result) => result.scenarioId),
      second.map((result) => result.scenarioId),
    );
    assert.deepEqual(
      first.map((result) => result.objectiveIds),
      second.map((result) => result.objectiveIds),
      "the same primitives produce the same objectives, in the same order",
    );
  } finally {
    tree.clean();
  }
});

test("generator: the matrix description is usable by a CLI", () => {
  const matrix = primitiveMatrix();
  const rows = matrix.primitives as { objectives: string[]; minutes: number; id: string }[];
  assert.equal(matrix.count, PRIMITIVES.size);
  assert.deepEqual(matrix.categories, ["hardware", "network", "os", "security", "software"]);
  for (const row of rows) {
    assert.ok(row.objectives.length > 0, `${row.id} lists its objectives`);
    assert.ok(row.minutes > 0, `${row.id} has a time budget`);
  }

  const combinations = matrix.combinations as { primitives: string[]; scenario_id: string }[];
  assert.ok(combinations.length > 0);
  for (const combo of combinations) {
    assert.ok(combo.primitives.length >= 2);
    assert.ok(combo.scenario_id.length > 0);
    for (const primitiveId of combo.primitives) {
      assert.ok(
        PRIMITIVES.has(primitiveId),
        `${combo.scenario_id} only names real primitives (${primitiveId})`,
      );
    }
  }
});
