"""Generated scenarios must be indistinguishable from hand-written ones, so the
central assertion here is: whatever the generator writes passes the same validation
the hand-written scenarios pass."""

from __future__ import annotations

import pytest

from ontrak.generator import GenerationError, generate, generate_matrix, primitive_matrix
from ontrak.primitives import PRIMITIVES, by_category, get, list_all
from ontrak.scenarios import ScenarioRepository


@pytest.fixture()
def repository(tmp_path) -> ScenarioRepository:
    root = tmp_path / "scenarios"
    root.mkdir()
    return ScenarioRepository(root)


# --------------------------------------------------------------------------- #
# the primitive library
# --------------------------------------------------------------------------- #


def test_primitives_cover_every_family():
    groups = by_category()
    assert {"hardware", "software", "network", "os", "security"} <= set(groups)


def test_every_primitive_has_a_reversible_setup_and_a_live_check():
    for primitive in list_all():
        assert primitive.briefing.strip(), primitive.id
        assert primitive.objectives, primitive.id
        assert primitive.check_ps.strip(), primitive.id
        assert primitive.setup_ps.strip(), primitive.id
        assert any(o.critical for o in primitive.objectives), (
            f"{primitive.id} has no critical objective; a scenario should have at "
            "least one thing the student must not miss"
        )
        # The check must reference each objective by the same id, or it would
        # silently score zero forever.
        for objective in primitive.objectives:
            assert f"'{objective.id}'" in primitive.check_ps, (primitive.id, objective.id)


def test_primitive_ids_are_unique():
    assert len(set(PRIMITIVES)) == len(PRIMITIVES)


def test_unknown_primitive_raises_with_the_available_list():
    with pytest.raises(KeyError, match="unknown fault primitive"):
        get("make-it-broken")


# --------------------------------------------------------------------------- #
# generation
# --------------------------------------------------------------------------- #


def test_generate_one_scenario_that_validates(repository):
    result = generate(["dns-resolver-trapped"], repository)
    assert result.ok, result.problems
    assert result.scenario_id == "dns-resolver-trapped"
    assert (result.directory / "scenario.yaml").exists()
    assert (result.directory / "setup.ps1").exists()
    assert (result.directory / "check.ps1").exists()

    scenario = repository.get("dns-resolver-trapped")
    assert scenario.category == "network"
    assert scenario.generated_from == ["dns-resolver-trapped"]
    assert [o.id for o in scenario.objectives] == result.objective_ids
    assert scenario.workload == ""


def test_generated_setup_confirms_success_and_check_writes_a_report(repository):
    result = generate(["service-disabled"], repository, scenario_id="gen-spooler")
    setup = (result.directory / "setup.ps1").read_text()
    check = (result.directory / "check.ps1").read_text()
    assert "Write-OnTrakSetupOk" in setup
    assert "OnTrak.Common.ps1" in setup and "OnTrak.Common.ps1" in check
    assert "Write-OnTrakReport" in check
    assert "Add-OnTrakCheck" in check
    assert "Generated by" in setup  # provenance: do not hand-edit


def test_generate_a_multi_fault_ticket(repository):
    result = generate(
        ["dns-resolver-trapped", "app-config-corrupt"],
        repository,
        scenario_id="gen-broken-workstation",
        title="Nothing works since this morning",
        intro="The user reports the machine is unusable after a remote support session.",
    )
    assert result.ok, result.problems
    scenario = repository.get("gen-broken-workstation")
    assert scenario.title == "Nothing works since this morning"
    assert "remote support session" in scenario.briefing
    # Two faults means both are represented, and the time budget adds up.
    assert len(scenario.objectives) >= 4
    assert scenario.minutes == 40
    assert scenario.difficulty == 3
    assert "generated" in scenario.tags


def test_regenerating_without_force_refuses_to_clobber(repository):
    generate(["service-disabled"], repository, scenario_id="one")
    with pytest.raises(GenerationError, match="already exists"):
        generate(["service-disabled"], repository, scenario_id="one")
    # ...and --force really replaces it.
    result = generate(["service-disabled"], repository, scenario_id="one", force=True)
    assert result.ok


def test_a_bad_scenario_id_is_rejected(repository):
    with pytest.raises(GenerationError, match="lowercase"):
        generate(["service-disabled"], repository, scenario_id="Not Slugged")


def test_an_empty_primitive_list_is_an_error(repository):
    with pytest.raises(GenerationError, match="at least one"):
        generate([], repository)


def test_duplicate_objective_ids_are_refused(repository, monkeypatch):
    from ontrak import generator
    from ontrak.primitives import Objective

    clash = get("service-disabled")
    monkeypatch.setitem(
        generator.PRIMITIVES,
        "clashing",
        type(clash)(
            id="clashing",
            label="clash",
            category="software",
            title="clash",
            briefing="clash",
            objectives=[Objective("spooler-start", "same id as the other primitive")],
            setup_ps="Write-OnTrakStep 'noop'",
            check_ps="Add-OnTrakCheck -Objective 'spooler-start' -Passed $false -Detail 'x'",
        ),
    )
    with pytest.raises(GenerationError, match="appears twice"):
        generate(["service-disabled", "clashing"], repository, scenario_id="dup")


def test_validating_the_result_can_be_skipped_for_speed(repository):
    result = generate(["service-disabled"], repository, scenario_id="raw", validate=False)
    assert result.problems == []
    assert (result.directory / "scenario.yaml").exists()


# --------------------------------------------------------------------------- #
# breadth pass
# --------------------------------------------------------------------------- #


def test_matrix_generates_a_valid_scenario_for_every_primitive(repository):
    results = generate_matrix(repository, prefix="gen")
    assert len(results) == len(list_all())
    problems = [p for result in results for p in result.problems]
    assert problems == [], problems
    # Every generated scenario is visible to the repository afterwards.
    ids = set(repository.ids())
    assert {r.scenario_id for r in results} <= ids


def test_matrix_is_repeatable(repository):
    first = generate_matrix(repository, prefix="gen")
    second = generate_matrix(repository, prefix="gen", force=True)
    assert [r.scenario_id for r in first] == [r.scenario_id for r in second]
    assert [r.objective_ids for r in first] == [r.objective_ids for r in second]


def test_primitive_matrix_description_is_usable_by_the_cli():
    matrix = primitive_matrix()
    assert matrix["count"] == len(PRIMITIVES)
    assert set(matrix["categories"]) == {"hardware", "software", "network", "os", "security"}
    for row in matrix["primitives"]:
        assert row["objectives"]
        assert row["minutes"] > 0
    for combo in matrix["combinations"]:
        assert len(combo["primitives"]) >= 2
        assert combo["scenario_id"]


def test_combination_suggestions_only_name_real_primitives():
    matrix = primitive_matrix()
    for combo in matrix["combinations"]:
        for primitive_id in combo["primitives"]:
            assert primitive_id in PRIMITIVES
