"""Scenario generation from fault primitives.

Two things this deliberately does *not* do: invent faults that were never reviewed,
and produce a scenario that cannot be graded. Every generated scenario is written in
the same shape as a hand-written one and then run through
:meth:`ScenarioRepository.validate`, so a generated scenario that would always score
zero fails generation instead of failing a student.

Use it for breadth (one scenario per primitive, covering the whole matrix) and for
variation (combine a network fault with a software fault to make a longer ticket).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from .models import Category
from .primitives import PRIMITIVES, FaultPrimitive, list_all
from .primitives import get as get_primitive
from .scenarios import ScenarioRepository

HEADER = "# Generated by `ontrak scenario generate`. Regenerate rather than hand-edit."


class GenerationError(RuntimeError):
    """Raised when a scenario cannot be generated safely."""


@dataclass
class GeneratedScenario:
    scenario_id: str
    directory: Path
    primitive_ids: list[str]
    objective_ids: list[str]
    category: str
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.strip().lower()).strip("-")


def _briefing_for(primitives: list[FaultPrimitive], title: str, intro: str = "") -> str:
    if len(primitives) == 1:
        return primitives[0].briefing
    lines = [intro.strip() or "Two faults have been reported on this machine.", ""]
    for index, item in enumerate(primitives, start=1):
        lines.append(f"{index}. {item.briefing.strip()}")
    lines += ["", f"Ticket title: {title}."]
    return "\n".join(lines)


def _ticket_for(primitives: list[FaultPrimitive], severity: str) -> dict:
    first = primitives[0]
    return {
        "reported_by": "User",
        "channel": "Service desk",
        "priority": severity,
        "summary": first.title if len(primitives) == 1 else "Multiple faults reported",
        "notes": [
            "Work the ticket the way you would on a real call; anything you change should be defensible.",
            "The grader reads live system state, so any correct fix counts.",
        ],
    }


def _setup_script(primitives: list[FaultPrimitive], scenario_id: str) -> str:
    parts = [
        HEADER,
        f"# Scenario: {scenario_id}",
        f"# Faults: {', '.join(p.id for p in primitives)}",
        "",
        '. "$PSScriptRoot\\..\\..\\lib\\OnTrak.Common.ps1"',
        "",
        "# Each injected fault is asserted straight after it is applied. `Require-OnTrak`",
        "# exits without writing the success marker when its check does not hold, and the",
        "# template build refuses to snapshot a setup that never confirmed -- so a fault",
        "# that silently does not land fails the build instead of reaching a student as a",
        "# ticket with nothing behind it.",
        "",
    ]
    for item in primitives:
        parts += [
            f"# --- {item.id}: {item.label} ---",
            f"Write-OnTrakStep 'applying {item.id}'",
            item.setup_ps.strip(),
            "",
        ]
        if item.assert_ps.strip():
            parts += [item.assert_ps.strip(), ""]
    parts += [
        "# Every setup script must confirm success; the template build rejects a",
        "# partially applied fault instead of handing a half-broken VM to a student.",
        "Write-OnTrakSetupOk -Note ('generated: ' + '" + ",".join(p.id for p in primitives) + "')",
        "",
    ]
    return "\n".join(parts)


def _check_script(primitives: list[FaultPrimitive], scenario_id: str) -> str:
    parts = [
        HEADER,
        f"# Scenario: {scenario_id}",
        "# Grading reads live state, so any correct fix passes.",
        "",
        '. "$PSScriptRoot\\..\\..\\lib\\OnTrak.Common.ps1"',
        "",
    ]
    for item in primitives:
        parts += [
            f"# --- {item.id}: {item.label} ---",
            item.check_ps.strip(),
            "",
        ]
    parts += ["Write-OnTrakReport", ""]
    return "\n".join(parts)


def _normalise_weights(weights: list[float]) -> list[float]:
    """Scale weights so they total exactly 100.

    Scenarios in this repository total 100 so the pass mark means the same thing
    everywhere. A primitive's own weights (3/2/1) are relative; composition has to
    turn them into a hundred-point budget, and the largest objective absorbs the
    rounding drift so the total is exact rather than 99.99.
    """
    total = float(sum(weights)) or 1.0
    scaled = [round(w * 100.0 / total, 2) for w in weights]
    drift = round(100.0 - sum(scaled), 2)
    if drift:
        index = max(range(len(scaled)), key=lambda i: scaled[i])
        scaled[index] = round(scaled[index] + drift, 2)
    return scaled


def _manifest(primitives: list[FaultPrimitive], scenario_id: str) -> dict:
    collected = []
    seen = set()
    for item in primitives:
        for objective in item.objectives:
            if objective.id in seen:
                raise GenerationError(
                    f"objective id {objective.id!r} appears twice; rename it in the primitive"
                )
            seen.add(objective.id)
            collected.append(objective)

    weights = _normalise_weights([objective.weight for objective in collected])
    objectives = [
        {
            "id": objective.id,
            "text": objective.text,
            "weight": weights[index],
            "critical": objective.critical,
        }
        for index, objective in enumerate(collected)
    ]

    categories = [p.category for p in primitives]
    primary = categories[0] if len(set(categories)) == 1 else (
        Category.SECURITY.value if Category.SECURITY.value in categories else categories[0]
    )
    difficulty = min(4, max(p.difficulty for p in primitives) + (1 if len(primitives) > 1 else 0))
    minutes = sum(p.minutes for p in primitives)
    hints = []
    for item in primitives:
        hints.extend(item.hints)

    devices: list[dict] = []
    config: dict = {}
    for item in primitives:
        for key in item.devices:
            devices.append({"name": key, "type": "disk", "options": {}})

    return {
        "id": scenario_id,
        "title": primitives[0].title if len(primitives) == 1 else "Multiple faults on one machine",
        "category": primary,
        "difficulty": difficulty,
        "minutes": minutes,
        "pass_score": 80,
        "briefing": _briefing_for(primitives, primitives[0].title),
        "ticket": _ticket_for(primitives, "Normal"),
        "objectives": objectives,
        "hints": hints,
        "tags": sorted({tag for item in primitives for tag in item.tags} | {"generated"}),
        "requires_internet": any(item.requires_internet for item in primitives),
        "reset_notes": "Reset destroys the session and clones a fresh VM from the clean template snapshot.",
        "generated_from": [item.id for item in primitives],
        "instance_devices": devices,
        "instance_config": config,
    }


def generate(
    primitive_ids: list[str],
    repository: ScenarioRepository,
    *,
    scenario_id: str | None = None,
    title: str | None = None,
    intro: str = "",
    force: bool = False,
    validate: bool = True,
) -> GeneratedScenario:
    """Compose primitives into a scenario directory and validate the result."""
    if not primitive_ids:
        raise GenerationError("at least one fault primitive is required")
    primitives = [get_primitive(pid) for pid in primitive_ids]

    if scenario_id is None:
        scenario_id = slug("-".join(primitive_ids))
    if scenario_id != slug(scenario_id):
        raise GenerationError(f"scenario id {scenario_id!r} must be lowercase and dash-separated")

    directory = Path(repository.root) / scenario_id
    if directory.exists() and not force:
        raise GenerationError(f"{directory} already exists; pass --force to overwrite")

    manifest = _manifest(primitives, scenario_id)
    if title:
        manifest["title"] = title
    if intro:
        manifest["briefing"] = _briefing_for(primitives, manifest["title"], intro)

    directory.mkdir(parents=True, exist_ok=True)
    (directory / "scenario.yaml").write_text(
        HEADER + "\n" + yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True, width=100)
    )
    (directory / "setup.ps1").write_text(_setup_script(primitives, scenario_id))
    (directory / "check.ps1").write_text(_check_script(primitives, scenario_id))

    result = GeneratedScenario(
        scenario_id=scenario_id,
        directory=directory,
        primitive_ids=list(primitive_ids),
        objective_ids=[str(o["id"]) for o in manifest["objectives"]],
        category=manifest["category"],
    )

    if validate:
        # Reload so validation sees the file we just wrote, not a cached catalogue.
        repository.reload()
        result.problems = repository.validate([scenario_id])
    return result


def generate_matrix(
    repository: ScenarioRepository,
    *,
    prefix: str = "gen",
    force: bool = False,
    validate: bool = True,
) -> list[GeneratedScenario]:
    """One scenario per primitive — the full breadth pass."""
    out = []
    for item in list_all():
        scenario_id = f"{prefix}-{slug(item.id)}"
        out.append(
            generate(
                [item.id],
                repository,
                scenario_id=scenario_id,
                force=force,
                validate=validate,
            )
        )
    return out


def suggest_combinations() -> list[list[str]]:
    """Curated multi-fault tickets: plausible pairs and triples, not random mixes."""
    return [
        ["dns-resolver-trapped", "service-disabled"],
        ["disk-space-exhausted", "startup-bloat"],
        ["proxy-hijacked", "app-config-corrupt"],
        ["malware-persistence", "malware-persistence"],
        # The plausible database pair: a network repair and a capacity lid on one
        # unhappy server. (Not db-service-stopped + anything SQL: the service being
        # down makes every other SQL fault's setup unreachable.)
        ["db-tcp-protocol-off", "db-log-capped"],
    ]


def primitive_matrix() -> dict[str, object]:
    """Descriptive view of what generation can produce, for docs and the CLI."""
    rows = []
    for item in list_all():
        rows.append(
            {
                "id": item.id,
                "label": item.label,
                "category": item.category,
                "category_label": item.category_label,
                "difficulty": item.difficulty,
                "minutes": item.minutes,
                "objectives": [o.id for o in item.objectives],
                "requires_internet": item.requires_internet,
                "notes": item.notes,
            }
        )
    return {
        "count": len(rows),
        "categories": sorted({row["category"] for row in rows}),
        "primitives": rows,
        "combinations": [
            {"primitives": combo, "scenario_id": slug("-".join(combo))}
            for combo in suggest_combinations()
            if len(set(combo)) == len(combo) and all(pid in PRIMITIVES for pid in combo)
        ],
    }
