/**
 * Scenario generation from fault primitives.
 *
 * Two things this deliberately does *not* do, in the lab's own words: invent faults that were
 * never reviewed, and produce a scenario that cannot be graded. Every generated scenario is
 * written in the same shape as a hand-written one and then run through the repository's
 * validator, so a generated scenario that would always score zero fails generation instead of
 * failing a student.
 *
 * Use it for breadth (one scenario per primitive, covering the whole matrix) and for variation
 * (combine a network fault with a software fault to make a longer ticket).
 *
 * THREE ADAPTATIONS from `generator.py`, each where the lab's shape cannot survive the port:
 *
 * - **The record is JSON, and the target directory is a parameter.** The Python read
 *   `repository.root` and wrote `scenario.yaml`; the port's repository is in-memory and pure
 *   (`scenarios.ts`) and the tree is JSON, so `generate` takes the tree's root and writes
 *   `<root>/<id>/scenario.json`. Nothing else about the layout changes: the two scripts land
 *   beside the record exactly as the lab put them, which is what makes a generated scenario a
 *   scenario the session manager can run.
 * - **Validation re-reads the tree, and hands the validator the scripts.** The Python called
 *   `repository.reload()`, which re-read the directory; the port's repository holds entries it
 *   was given, so generation re-reads with `scenarioEntriesFrom` and builds a fresh repository
 *   over what is now on disk — which also means the validator can be given each scenario's
 *   `ScenarioFiles` (its `setup.ps1`/`check.ps1` text), so the *script* contract is checked and
 *   not just the record's. A generated scenario whose check script does not report its
 *   objectives is therefore refused here, as it should be.
 * - **The generator's header line lives in the scripts.** JSON has no comments, so the lab's
 *   "Generated by `ontrak scenario generate`. Regenerate rather than hand-edit." is written
 *   into `setup.ps1` and `check.ps1` — the files a human would be tempted to edit — while the
 *   record carries the machine-readable half of the same fact, `generated_from`.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { CATEGORY_LABELS, type Category } from "./models";
import { scenarioEntriesFrom, scenarioFilesFor } from "./dataset";
import { getPrimitive, listPrimitives, type FaultPrimitive } from "./primitives";
import { ScenarioRepository } from "./scenarios";

export class GenerationError extends Error {}

/** The line the lab stamped every generated file with. */
export const HEADER = "# Generated by `ontrak scenario generate`. Regenerate rather than hand-edit.";

export class GeneratedScenario {
  constructor(
    readonly scenarioId: string,
    readonly directory: string,
    readonly primitiveIds: string[],
    readonly objectiveIds: string[],
    readonly category: string,
    readonly problems: string[] = [],
  ) {}

  /** True when nothing the validator said would stop this scenario being graded. */
  get ok(): boolean {
    return this.problems.length === 0;
  }
}

/** A lowercase, dash-separated identifier, the lab's own rule for what a scenario id may be. */
export function slug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** The student's brief: one fault reads as itself, several read as a numbered list. */
export function briefingFor(
  primitives: readonly FaultPrimitive[],
  title: string,
  intro = "",
): string {
  const first = primitives[0];
  if (primitives.length === 1 && first) return first.briefing;
  const lines = [intro.trim() || "Two faults have been reported on this machine.", ""];
  primitives.forEach((item, index) => {
    lines.push(`${index + 1}. ${item.briefing.trim()}`);
  });
  lines.push("", `Ticket title: ${title}.`);
  return lines.join("\n");
}

/** The ticket header. `severity` is the priority the desk would have recorded. */
export function ticketFor(
  primitives: readonly FaultPrimitive[],
  severity: string,
): Record<string, unknown> {
  const first = primitives[0];
  return {
    reported_by: "User",
    channel: "Service desk",
    priority: severity,
    summary: primitives.length === 1 ? (first?.title ?? "") : "Multiple faults reported",
    notes: [
      "Work the ticket the way you would on a real call; anything you change should be defensible.",
      "The grader reads live system state, so any correct fix counts.",
    ],
  };
}

export function setupScript(primitives: readonly FaultPrimitive[], scenarioId: string): string {
  const parts = [
    HEADER,
    `# Scenario: ${scenarioId}`,
    `# Faults: ${primitives.map((item) => item.id).join(", ")}`,
    "",
    '. "$PSScriptRoot\\..\\..\\lib\\OnTrak.Common.ps1"',
    "",
  ];
  for (const item of primitives) {
    parts.push(
      `# --- ${item.id}: ${item.label} ---`,
      `Write-OnTrakStep 'applying ${item.id}'`,
      item.setupPs.trim(),
      "",
    );
  }
  parts.push(
    "# Every setup script must confirm success; the template build rejects a",
    "# partially applied fault instead of handing a half-broken VM to a student.",
    `Write-OnTrakSetupOk -Note ('generated: ' + '${primitives.map((item) => item.id).join(",")}')`,
    "",
  );
  return parts.join("\n");
}

export function checkScript(primitives: readonly FaultPrimitive[], scenarioId: string): string {
  const parts = [
    HEADER,
    `# Scenario: ${scenarioId}`,
    "# Grading reads live state, so any correct fix passes.",
    "",
    '. "$PSScriptRoot\\..\\..\\lib\\OnTrak.Common.ps1"',
    "",
  ];
  for (const item of primitives) {
    parts.push(`# --- ${item.id}: ${item.label} ---`, item.checkPs.trim(), "");
  }
  parts.push("Write-OnTrakReport", "");
  return parts.join("\n");
}

/**
 * Scale weights so they total exactly 100.
 *
 * Scenarios in this repository total 100 so the pass mark means the same thing everywhere. A
 * primitive's own weights (3/2/1) are relative; composition has to turn them into a
 * hundred-point budget, and the largest objective absorbs the rounding drift so the total is
 * exact rather than 99.99 — which matters because the grader's own weighting has no tolerance
 * for a budget that does not close.
 */
export function normaliseWeights(weights: readonly number[]): number[] {
  const total = weights.reduce((sum, weight) => sum + weight, 0) || 1;
  const scaled = weights.map((weight) => round2((weight * 100) / total));
  const drift = round2(100 - scaled.reduce((sum, weight) => sum + weight, 0));
  if (drift !== 0) {
    let largest = 0;
    for (let index = 1; index < scaled.length; index += 1) {
      if ((scaled[index] ?? 0) > (scaled[largest] ?? 0)) largest = index;
    }
    scaled[largest] = round2((scaled[largest] ?? 0) + drift);
  }
  return scaled;
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

/** The record a generated scenario is written as: one scenario, in the on-disk shape. */
export function manifestFor(
  primitives: readonly FaultPrimitive[],
  scenarioId: string,
): Record<string, unknown> {
  const collected: FaultPrimitive["objectives"] = [];
  const seen = new Set<string>();
  for (const item of primitives) {
    for (const objective of item.objectives) {
      if (seen.has(objective.id)) {
        throw new GenerationError(
          `objective id ${JSON.stringify(objective.id)} appears twice; rename it in the primitive`,
        );
      }
      seen.add(objective.id);
      collected.push(objective);
    }
  }

  const weights = normaliseWeights(collected.map((objective) => objective.weight));
  const objectives = collected.map((objective, index) => ({
    id: objective.id,
    text: objective.text,
    weight: weights[index],
    critical: objective.critical,
  }));

  const categories = primitives.map((item) => item.category);
  const distinct = new Set(categories);
  const primary: Category =
    distinct.size === 1
      ? (categories[0] ?? "software")
      : categories.includes("security")
        ? "security"
        : (categories[0] ?? "software");

  const difficulty = Math.min(
    4,
    Math.max(...primitives.map((item) => item.difficulty)) + (primitives.length > 1 ? 1 : 0),
  );
  const minutes = primitives.reduce((sum, item) => sum + item.minutes, 0);
  const hints = primitives.flatMap((item) => item.hints);
  // A primitive's `devices` are names of extra instances the fault needs; the lab turned each
  // into a disk device with no options, which is what the shape means here too.
  const devices = primitives.flatMap((item) =>
    item.devices.map((name) => ({ name, type: "disk", options: {} })),
  );
  const title = primitives.length === 1 ? (primitives[0]?.title ?? scenarioId) : "Multiple faults on one machine";

  return {
    id: scenarioId,
    title,
    category: primary,
    difficulty,
    minutes,
    pass_score: 80,
    briefing: briefingFor(primitives, title),
    ticket: ticketFor(primitives, "Normal"),
    objectives,
    hints,
    tags: [...new Set([...primitives.flatMap((item) => item.tags), "generated"])].sort(),
    requires_internet: primitives.some((item) => item.requiresInternet),
    reset_notes:
      "Reset destroys the session and clones a fresh VM from the clean template snapshot.",
    generated_from: primitives.map((item) => item.id),
    instance_devices: devices,
    instance_config: {},
  };
}

export interface GenerateOptions {
  /** The scenario tree to write into: `<root>/<scenarioId>/…`. Required, never guessed. */
  root: string;
  scenarioId?: string;
  title?: string;
  intro?: string;
  /** Overwrite an existing directory. Without it, an existing scenario is an error. */
  force?: boolean;
  /** Run the result through the repository's validator. On by default. */
  validate?: boolean;
}

/** Compose primitives into a scenario directory and validate the result. */
export function generate(
  primitiveIds: readonly string[],
  options: GenerateOptions,
): GeneratedScenario {
  if (primitiveIds.length === 0) {
    throw new GenerationError("at least one fault primitive is required");
  }
  const primitives = primitiveIds.map((id) => getPrimitive(id));

  const scenarioId = options.scenarioId ?? slug(primitiveIds.join("-"));
  if (scenarioId !== slug(scenarioId)) {
    throw new GenerationError(
      `scenario id ${JSON.stringify(scenarioId)} must be lowercase and dash-separated`,
    );
  }

  const directory = join(options.root, scenarioId);
  if (existsSync(directory) && options.force !== true) {
    throw new GenerationError(`${directory} already exists; pass --force to overwrite`);
  }

  const manifest = manifestFor(primitives, scenarioId);
  if (options.title !== undefined && options.title !== "") manifest.title = options.title;
  if (options.intro !== undefined && options.intro !== "") {
    manifest.briefing = briefingFor(primitives, String(manifest.title), options.intro);
  }

  mkdirSync(directory, { recursive: true });
  writeFileSync(join(directory, "scenario.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  writeFileSync(join(directory, "setup.ps1"), setupScript(primitives, scenarioId), "utf8");
  writeFileSync(join(directory, "check.ps1"), checkScript(primitives, scenarioId), "utf8");

  const result = new GeneratedScenario(
    scenarioId,
    directory,
    [...primitiveIds],
    (manifest.objectives as { id: string }[]).map((objective) => objective.id),
    String(manifest.category),
  );

  if (options.validate !== false) {
    // Read the tree back rather than trusting what was just written: that is what makes the
    // check below about the files a host will load, and it is what lets the *scripts* be
    // validated instead of only the record.
    const repository = new ScenarioRepository(scenarioEntriesFrom(options.root));
    const written = repository.list().filter((scenario) => scenario.id === scenarioId);
    const files = new Map(written.map((scenario) => [scenario.id, scenarioFilesFor(scenario, options.root)]));
    result.problems.push(...repository.validate([scenarioId], { files }));
  }
  return result;
}

/** One scenario per primitive — the full breadth pass. */
export function generateMatrix(
  options: Omit<GenerateOptions, "scenarioId"> & { prefix?: string },
): GeneratedScenario[] {
  const prefix = options.prefix ?? "gen";
  return listPrimitives().map((item) =>
    generate([item.id], { ...options, scenarioId: `${prefix}-${slug(item.id)}` }),
  );
}

/**
 * Curated multi-fault tickets: plausible pairs and triples, not random mixes.
 *
 * The last one pairs a fault with itself, which is the lab's own list and a deliberate case:
 * `generate` refuses a repeated objective id, so it is how "the same primitive twice" surfaces
 * as an error rather than as a ticket whose two halves grade each other.
 */
export function suggestedCombinations(): string[][] {
  return [
    ["dns-resolver-trapped", "service-disabled"],
    ["disk-space-exhausted", "startup-bloat"],
    ["proxy-hijacked", "app-config-corrupt"],
    ["malware-persistence", "malware-persistence"],
  ];
}

/** A descriptive view of what generation can produce, for docs and the CLI. */
export function primitiveMatrix(): Record<string, unknown> {
  const rows = listPrimitives().map((item) => ({
    id: item.id,
    label: item.label,
    category: item.category,
    // The Python's `category_label` returned the category value itself
    // (`Category(self.category).value`), which made it a duplicate column; the model's own
    // label is what a table wants, and using it is a named divergence rather than a silent one.
    category_label: CATEGORY_LABELS[item.category] ?? item.category,
    difficulty: item.difficulty,
    minutes: item.minutes,
    objectives: item.objectives.map((objective) => objective.id),
    requires_internet: item.requiresInternet,
    notes: item.notes,
  }));
  const known = new Set(rows.map((row) => row.id));
  return {
    count: rows.length,
    categories: [...new Set(rows.map((row) => row.category))].sort(),
    primitives: rows,
    combinations: suggestedCombinations()
      .filter((combo) => new Set(combo).size === combo.length && combo.every((id) => known.has(id)))
      .map((combo) => ({ primitives: combo, scenario_id: slug(combo.join("-")) })),
  };
}
